title: 吕钰  Lv, Yu  # your name (or website title) here
logo: "/images/logo_lvyu.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  副研究员， 非线性力学国家重点实验室，中科院力学所; Associate Professor, LNM, IMECH, CAS
  <br><br>
  2017-2021年， 助理教授，航空航天系，   密西西比州立大学 <br>
  2016-2017年， 博士后，   湍流研究中心，斯坦福大学  <br>
  2013-2016年， 博士，      机械工程系，    斯坦福大学
  <br><br>
  "Email: lvyu@imech.ac.cn"
 <br>
  <a href="https://scholar.google.com/citations?user=I6YBiacAAAAJ&hl=en">View My Googler Scholar Profile</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
